# Generated by Django 3.1.14 on 2024-01-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('second_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('second_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('second_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=25)),
                ('meeting_place', models.CharField(max_length=85)),
                ('target_address', models.CharField(max_length=85)),
                ('cancellation_comment', models.CharField(max_length=256)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.courier')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('item_receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.itemreceiver')),
                ('item_sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.itemsender')),
            ],
        ),
    ]
